METRO_AREAS = {
        "Seattle, Washington" : ["King, Washington", "Snohomish, Washington", "Pierce, Washington", "Thurston, Washington", "Kitsap, Washington"],
        "Los Angeles, California" : ["Los Angeles, California", "Orange, California", "Ventura, California", "Riverside, California", "San Diego, California"],
        "Boston, Massachusetts" : ["Middlesex, Massachusetts", "Essex, Massachusetts", "Suffolk, Massachusetts", "Norfolk, Massachusetts"],
        "New York City, New York" : ["New York City, New York", "Nassau, New York", "Westchester, New York", "Bergen, New Jersey", "Suffolk, New York", "Hudson, New Jersey", "Essex, New Jersey", "Union, New Jersey", "Middlesex, New Jersey"],
        "Philadelphia, Pennsylvania" : ["Philadelphia, Pennsylvania", "Bucks, Pennsylvania", "Montgomery, Pennsylvania", "Delaware, Pennsylvania", "Burlington, New Jersey", "Camden, New Jersey", "Gloucester, New Jersey"],
        "New Orleans, Louisiana" : ["Jefferson, Louisiana", "Orleans, Louisiana", "Plaquemines, Louisiana"],
        "Atlanta, Georgia" : ["Newton, Georgia", "Gwinnett, Georgia", "Walton, Georgia", "Henry, Georgia", "DeKalb, Georgia", "Cobb, Georgia", "Clayton, Georgia", "Douglas, Georgia", "Fayette, Georgia", "Henry, Georgia", "Forsyth, Georgia"],
        "Detroit, Michigan" : ["Wayne, Michigan", "Oakland, Michigan", "Macomb, Michigan", "Washtenaw, Michigan", "Kent, Michigan", "Genesee, Michigan", "Ingham, Michigan", "Monroe, Michigan"],
        "San Francisco, California" : ["Alameda, California", "Contra Costa, California", "Marin, California", "Napa, California", "San Francisco, California", "Solano, California", "San Mateo, California", "Santa Clara, California", "Sonoma, California"],
        "Nashville, Tennessee" : ["Davidson, Tennessee", "Cheatham, Tennessee", "Dickson, Tennessee", "Maury, Tennessee", "Montgomery, Tennessee", "Robertson, Tennessee", "Rutherford, Tennessee", "Sumner, Tennessee"],
        "Chicago, Illinois" : ["Cook, Illinois", "Lake, Illinois", "McHenry, Illinois", "DuPage, Illinois", "Kane, Illinois", "Kendall, Illinois", "Grundy, Illinois", "Will, Illinois", "Kankakee, Illinois", "Lake, Indiana", "Porter, Indiana", "LaPorte, Indiana"]
    }


ABBV_TO_STATE = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming'

    }